#ifndef _LMF_CONVERSATION_H
#define _LMF_CONVERSATION_H

typedef struct _LMF_CONVERSATION_STRUCT {
	LMF_PRIVATE_KEY my_key;
	LMF_PUBLIC_KEY their_key;
	LMF_OUTBOUND_MESSAGE_STACK queue;
	LMF_MESSAGE_STACK sent;
	LMF_MESSAGE_STACK received;
} * LMF_CONVERSATION;

LMF_OUTBOUND_MESSAGE next_LMF_OUTBOUND_MESSAGE(LMF_CONVERSATION conversation);

LMF_OUTBOUND_RESPONSE next_LMF_OUTBOUND_RESPONSE(LMF_CONVERSATION conversation);

#endif
