#ifndef _LMF_RESPONSE_ISSUE_TYPES_H
#define _LMF_RESPONSE_ISSUE_TYPES_H

#define LMF_UNKNOWN_RESPONSE_ISSUE_TYPE 0

typedef struct _LMF_UNEXPECTED_RESPONSE_ISSUE_STRUCT {
	LMF_RESPONSE_TYPE_STACK expected;
} * LMF_UNEXPECTED_RESPONSE_ISSUE;
#define LMF_UNEXPECTED_RESPONSE_ISSUE_TYPE 1

#endif
